version: "3.1"

services:
  devcontainer:
    image: ghcr.io/moveaxlab/oracle-devcontainer:latest
    volumes:
      - .:/workspaces/oracle:cached
    command: sleep infinity

  oracle-19c:
    image: ghcr.io/oracle/adb-free:latest  # https://github.com/oracle/adb-free
    ports:
      - 1521:1521
    environment:
      ADMIN_PASSWORD: TVDGXvpzQat8
      WALLET_PASSWORD: tkmXp6Ug

  oracle-23c:
    image: container-registry.oracle.com/database/free:latest
    ports:
      - 1522:1521
    environment:
      ORACLE_PWD: password

